import { Achievement } from '../types/finance';

/**
 * Расширяемый список ачивок.
 * Чтобы добавить новую ачивку в будущем, достаточно просто добавить объект в этот массив!
 */
export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_step',
    title: 'Первый шаг к контролю',
    description: 'Внесите свою первую операцию расхода или дохода',
    category: 'habit',
    icon: 'Sparkles',
    targetCount: 1,
    currentProgress: 0,
    isUnlocked: false,
    rewardXp: 50,
    ruleType: 'first_transaction',
  },
  {
    id: 'streak_3_days',
    title: 'Холодный расчёт',
    description: '3 дня подряд без импульсивных трат (метки Impulse)',
    category: 'discipline',
    icon: 'Shield',
    targetCount: 3,
    currentProgress: 0,
    isUnlocked: false,
    rewardXp: 150,
    ruleType: 'streak_no_impulse',
  },
  {
    id: 'streak_7_days',
    title: 'Железный контроль',
    description: '7 дней подряд без единой неразумной траты',
    category: 'discipline',
    icon: 'ShieldCheck',
    targetCount: 7,
    currentProgress: 0,
    isUnlocked: false,
    rewardXp: 350,
    ruleType: 'streak_no_impulse',
  },
  {
    id: 'streak_14_days',
    title: 'Дзен самурая',
    description: '14 дней осознанного потребления без импульсов',
    category: 'discipline',
    icon: 'Flame',
    targetCount: 14,
    currentProgress: 0,
    isUnlocked: false,
    rewardXp: 800,
    ruleType: 'streak_no_impulse',
  },
  {
    id: 'multi_currency_master',
    title: 'Мультивалютный магнат',
    description: 'Заведите счета как минимум в 2 разных валютах (например, RUB и USD)',
    category: 'wealth',
    icon: 'Globe',
    targetCount: 2,
    currentProgress: 0,
    isUnlocked: false,
    rewardXp: 100,
    ruleType: 'multi_currency_accounts',
  },
  {
    id: 'savings_guardian',
    title: 'Хранитель капитала',
    description: 'Создайте накопительный счет или вклад под процент',
    category: 'wealth',
    icon: 'PiggyBank',
    targetCount: 1,
    currentProgress: 0,
    isUnlocked: false,
    rewardXp: 120,
    ruleType: 'savings_created',
  },
  {
    id: 'master_of_transfers',
    title: 'Капиталовложение',
    description: 'Совершите первый перевод между своими счетами или конвертацию валюты',
    category: 'wealth',
    icon: 'ArrowRightLeft',
    targetCount: 1,
    currentProgress: 0,
    isUnlocked: false,
    rewardXp: 80,
    ruleType: 'first_transfer',
  },
  {
    id: 'habit_10_logs',
    title: 'Педантичный бухгалтер',
    description: 'Внесите 10 любых финансовых операций в журнал',
    category: 'habit',
    icon: 'CheckCircle2',
    targetCount: 10,
    currentProgress: 0,
    isUnlocked: false,
    rewardXp: 150,
    ruleType: 'total_logged',
  },
  {
    id: 'low_impulse_ratio',
    title: 'Разумный гедонист',
    description: 'Доля импульсивных трат за последние 30 дней составляет менее 15% от всех расходов',
    category: 'anti_impulse',
    icon: 'TrendingDown',
    targetCount: 1,
    currentProgress: 0,
    isUnlocked: false,
    rewardXp: 500,
    ruleType: 'low_impulse_month',
  },
];
